#!/bin/sh
echo "[Git Hooks][Pre-Push] 실행"

changed_file_by_prettier=$(npx prettier --list-different .)
if [ -z "$changed_file_by_prettier" ]; then
    echo "[Git Hooks][Pre-Push] no files to git add"

else
    npx prettier --write .
    while IFS= read -r file; do
        echo "[Git Hooks][Pre-Push] git add $file"
        git add "$file"
    done <<< "$changed_file_by_prettier"
  
    git commit -m "Formatting : Prettier is auto-work by git hooks"
    echo "[Git Hooks][Pre-Push] git commit -m \"Formatting : Prettier is auto-work by git hooks\""
fi
